# Use a base image with Node.js installed
FROM node:alpine

# Install ganache globally
RUN npm install -g ganache

# Set the working directory
WORKDIR /app

# Copy your data directory if needed
# COPY ./data/save /app/data/save

# Set the command to run ganache with your desired options
CMD ["ganache", "-i=1337", "--mnemonic=swim lab spawn angle cigar victory syrup radar cupboard crisp erase dizzy", "--host", "0.0.0.0", "--gasLimit=5000000"]
